# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Cargo Dependencies
    init: |
      cargo fetch
      cargo build
  - name: Cargo binaries
    init: |
      cargo install cargo-audit cargo-outdated
  - name: Rustup components
    init: |
      rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
