name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-default:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Default Docker image
      run: docker build .

  build-slim:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Slim Docker image
      run: docker build --build-arg BUILD_EXTENSION="-slim" --build-arg EXPORT_EXTENSION="stable-slim" .
