name: Semantic Version

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Default
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run: docker buildx build --platform=linux/amd64,linux/arm64/v8 --push --tag chweicki/noria-server:$VERSION .
    - name: Build Slim
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run:  docker buildx build --platform=linux/amd64,linux/arm64/v8 --push --build-arg BUILD_EXTENSION="-slim" --build-arg EXPORT_EXTENSION="stable-slim" --tag chweicki/noria-server:$VERSION-slim .